
FROM openjdk:17
WORKDIR /usr/local/lib
COPY /target/SpringBootApp-1.0-SNAPSHOT.jar /usr/local/lib/SpringBootApp-1.0-SNAPSHOT.jar
EXPOSE 8080
CMD ["java","-jar","/usr/local/lib/SpringBootApp-1.0-SNAPSHOT.jar"]